sudo: required
services:
  - docker

env:
  - DOCKER_REPO_SLUG=ngaxavi/node-kubectl-skaffold-dind

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t $DOCKER_REPO_SLUG:latest .
  - docker push $DOCKER_REPO_SLUG:latest
