name: Docker Build and Push
on:
  push:
    branches:
      - master
jobs:
  build_push_dockerhub:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ngaxavi/node-kubectl-skaffold-dind
          tags: v1.14, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
